"""Initial migration

Revision ID: f56623800d20
Revises: 
Create Date: 2020-05-17 20:56:52.530064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56623800d20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_string', sa.String(length=256), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('mark_alloc', sa.Integer(), nullable=True),
    sa.Column('question_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('is_marked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('questions')
    op.drop_table('tests')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
